AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  YourBirthdayDate:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: YourBirthdayDate
      Timeout: 30
      Handler: com.eltonkola.alexa.birthdayguru.BirthdayStreamHandler
      Runtime: java8
      CodeUri: target//birthdayguru-1.0-jar-with-dependencies.jar
      Policies:
      - AWSLambdaExecute
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /hello/{proxy+}
            Method: any
  ExampleApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: swagger.yaml
Outputs:
  ExampleApi:
    Description: API URI
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello'
    Export:
      Name: ExampleApi